#!/bin/bash

# sysinfo_page - A script to produce an HTML file
# this one actually adds the - in <<-
cat <<- _EOF_
    <html>
    <head>
        <title>
        The title of your page
        </title>
    </head>

    <body>
        Your page content goes here.
    </body>
    </html>
_EOF_
